### ISSUE TITLE
take gym off entryway group

### ISSUE THREAD

**Issue by ezeckner** [PurelyNicole/homeassistant-config#5]

**Comment by ezeckner** [comment]
completed

**Comment by PurelyNicole** [comment]
Needs to be added to it's own group as well.

**Comment by ezeckner** [comment]
it's already included in the sleep scene, is anything else really needed to handle turning it off?

**Comment by PurelyNicole** [comment]
Is it in away scene? Do you want it to display in UI?

**Comment by ezeckner** [comment]
added to away scene
